version: 2
jobs:
  build:
    docker:
      - image: cimg/node:22.11

    working_directory: ~/repo

    steps:
      - checkout

      - run: corepack enable pnpm

      - restore_cache:
          keys:
          - v1-pnpm-{{ checksum "pnpm-lock.yaml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-pnpm-

      - run: pnpm install --frozen-lockfile

      - save_cache:
          paths:
            - ~/.local/share/pnpm/store
          key: v1-pnpm-{{ checksum "pnpm-lock.yaml" }}

      - run: pnpm test
